import type { CareNeed, Clinic, Neighbourhood, SpokenLanguage } from "../../types/doctor";

/**
 * ILLUSTRATIVE DIRECTORY. These clinics are fictional and exist to demonstrate
 * the matching engine. Ontario has no public API of practices accepting
 * patients; real matching happens through Health Care Connect (ontario.ca, or
 * call 811). Replace CLINICS with a live source when one is available.
 */

/** Approximate neighbourhood centroids in Ottawa. */
export const NEIGHBOURHOODS: Neighbourhood[] = [
  { id: "centretown", label: "Centretown", location: { lat: 45.4145, lon: -75.6972 } },
  { id: "byward", label: "ByWard Market / Lowertown", location: { lat: 45.4291, lon: -75.6925 } },
  { id: "sandy-hill", label: "Sandy Hill", location: { lat: 45.4228, lon: -75.681 } },
  { id: "glebe", label: "The Glebe", location: { lat: 45.4003, lon: -75.6896 } },
  { id: "vanier", label: "Vanier", location: { lat: 45.439, lon: -75.663 } },
  { id: "hintonburg", label: "Hintonburg", location: { lat: 45.404, lon: -75.73 } },
  { id: "westboro", label: "Westboro", location: { lat: 45.3925, lon: -75.756 } },
  { id: "alta-vista", label: "Alta Vista", location: { lat: 45.383, lon: -75.656 } },
  { id: "nepean", label: "Nepean (Centrepointe)", location: { lat: 45.344, lon: -75.759 } },
  { id: "orleans", label: "Orléans", location: { lat: 45.476, lon: -75.513 } },
  { id: "kanata", label: "Kanata", location: { lat: 45.3088, lon: -75.8987 } },
  { id: "barrhaven", label: "Barrhaven", location: { lat: 45.275, lon: -75.744 } },
  { id: "riverside-south", label: "Riverside South", location: { lat: 45.271, lon: -75.686 } },
  { id: "stittsville", label: "Stittsville", location: { lat: 45.262, lon: -75.923 } },
];

export const LANGUAGES: SpokenLanguage[] = [
  "English",
  "French",
  "Arabic",
  "Mandarin",
  "Cantonese",
  "Somali",
  "Spanish",
  "Punjabi",
  "Tagalog",
  "Persian",
  "Portuguese",
  "Ukrainian",
];

export const CARE_NEEDS: Array<{ id: CareNeed; label: string }> = [
  { id: "chronic-conditions", label: "Chronic conditions (e.g. diabetes, heart disease)" },
  { id: "mental-health", label: "Mental health" },
  { id: "prenatal", label: "Pregnancy & prenatal care" },
  { id: "pediatrics", label: "Care for children" },
  { id: "seniors", label: "Older adult care" },
  { id: "lgbtq2s", label: "2SLGBTQI+ affirming care" },
  { id: "newcomer", label: "Newcomer & refugee health" },
  { id: "substance-use", label: "Substance use support" },
  { id: "disability", label: "Disability-informed care" },
];

const point = (lat: number, lon: number) => ({ lat, lon });

export const CLINICS: Clinic[] = [
  {
    id: "c-maplegrove",
    name: "Maple Grove Family Practice",
    neighbourhood: "Centretown",
    location: point(45.4128, -75.6951),
    providerType: "family-physician",
    providers: 4,
    acceptingStatus: "waitlist",
    waitlistLength: 42,
    typicalWaitWeeks: 10,
    languages: ["English", "French", "Arabic"],
    services: ["chronic-conditions", "mental-health", "newcomer"],
    wheelchairAccessible: true,
    eveningHours: true,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-birchwood",
    name: "Birchwood Health Team",
    neighbourhood: "Vanier",
    location: point(45.4372, -75.6655),
    providerType: "team",
    providers: 9,
    acceptingStatus: "accepting",
    waitlistLength: 6,
    typicalWaitWeeks: 3,
    languages: ["English", "French", "Somali", "Arabic"],
    services: ["chronic-conditions", "mental-health", "substance-use", "newcomer", "disability"],
    wheelchairAccessible: true,
    eveningHours: false,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-cedarpoint",
    name: "Cedar Point Nurse Practitioner Clinic",
    neighbourhood: "Sandy Hill",
    location: point(45.4217, -75.6789),
    providerType: "nurse-practitioner",
    providers: 3,
    acceptingStatus: "accepting",
    waitlistLength: 3,
    typicalWaitWeeks: 2,
    languages: ["English", "French", "Spanish"],
    services: ["lgbtq2s", "mental-health", "prenatal"],
    wheelchairAccessible: false,
    eveningHours: true,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-lakeside",
    name: "Lakeside Community Health",
    neighbourhood: "Westboro",
    location: point(45.3911, -75.7588),
    providerType: "team",
    providers: 7,
    acceptingStatus: "waitlist",
    waitlistLength: 88,
    typicalWaitWeeks: 20,
    languages: ["English", "French", "Portuguese"],
    services: ["seniors", "chronic-conditions", "disability"],
    wheelchairAccessible: true,
    eveningHours: false,
    virtualCare: false,
    sample: true,
  },
  {
    id: "c-riverbend",
    name: "Riverbend Family Clinic",
    neighbourhood: "Alta Vista",
    location: point(45.3852, -75.6531),
    providerType: "family-physician",
    providers: 5,
    acceptingStatus: "accepting",
    waitlistLength: 12,
    typicalWaitWeeks: 4,
    languages: ["English", "Mandarin", "Cantonese"],
    services: ["pediatrics", "prenatal", "chronic-conditions"],
    wheelchairAccessible: true,
    eveningHours: true,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-northstar",
    name: "Northstar Medical Group",
    neighbourhood: "Orléans",
    location: point(45.4731, -75.5188),
    providerType: "family-physician",
    providers: 6,
    acceptingStatus: "waitlist",
    waitlistLength: 30,
    typicalWaitWeeks: 8,
    languages: ["English", "French", "Tagalog"],
    services: ["pediatrics", "seniors", "chronic-conditions"],
    wheelchairAccessible: true,
    eveningHours: true,
    virtualCare: false,
    sample: true,
  },
  {
    id: "c-sprucehill",
    name: "Spruce Hill Family Health",
    neighbourhood: "Kanata",
    location: point(45.3102, -75.9041),
    providerType: "team",
    providers: 8,
    acceptingStatus: "accepting",
    waitlistLength: 15,
    typicalWaitWeeks: 5,
    languages: ["English", "Punjabi", "Persian"],
    services: ["pediatrics", "chronic-conditions", "mental-health"],
    wheelchairAccessible: true,
    eveningHours: false,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-willowbrook",
    name: "Willowbrook Nurse Practitioner Clinic",
    neighbourhood: "Barrhaven",
    location: point(45.2771, -75.7402),
    providerType: "nurse-practitioner",
    providers: 2,
    acceptingStatus: "accepting",
    waitlistLength: 1,
    typicalWaitWeeks: 1,
    languages: ["English", "Arabic"],
    services: ["prenatal", "pediatrics"],
    wheelchairAccessible: true,
    eveningHours: true,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-harbourview",
    name: "Harbourview Medical Centre",
    neighbourhood: "Hintonburg",
    location: point(45.4051, -75.7279),
    providerType: "family-physician",
    providers: 3,
    acceptingStatus: "closed",
    waitlistLength: 0,
    typicalWaitWeeks: 0,
    languages: ["English", "French"],
    services: ["chronic-conditions", "seniors"],
    wheelchairAccessible: true,
    eveningHours: false,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-oakridge",
    name: "Oakridge Health Collective",
    neighbourhood: "Nepean (Centrepointe)",
    location: point(45.3452, -75.7611),
    providerType: "team",
    providers: 10,
    acceptingStatus: "waitlist",
    waitlistLength: 55,
    typicalWaitWeeks: 14,
    languages: ["English", "French", "Ukrainian", "Spanish"],
    services: ["mental-health", "substance-use", "newcomer", "lgbtq2s"],
    wheelchairAccessible: true,
    eveningHours: true,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-glenview",
    name: "Glenview Family Doctors",
    neighbourhood: "The Glebe",
    location: point(45.3991, -75.6874),
    providerType: "family-physician",
    providers: 2,
    acceptingStatus: "waitlist",
    waitlistLength: 24,
    typicalWaitWeeks: 12,
    languages: ["English", "French"],
    services: ["seniors", "mental-health"],
    wheelchairAccessible: false,
    eveningHours: false,
    virtualCare: true,
    sample: true,
  },
  {
    id: "c-southgate",
    name: "Southgate Primary Care",
    neighbourhood: "Riverside South",
    location: point(45.2728, -75.6843),
    providerType: "team",
    providers: 6,
    acceptingStatus: "accepting",
    waitlistLength: 9,
    typicalWaitWeeks: 4,
    languages: ["English", "Somali", "Arabic", "French"],
    services: ["newcomer", "pediatrics", "chronic-conditions", "prenatal"],
    wheelchairAccessible: true,
    eveningHours: false,
    virtualCare: true,
    sample: true,
  },
];

export const HEALTH_CARE_CONNECT_URL = "https://www.ontario.ca/page/find-family-doctor-or-nurse-practitioner";
