import { useMemo, useState } from "react";
import { Droplets, ExternalLink, RefreshCw, TrafficCone, TrainFront, Zap, Activity } from "lucide-react";
import { SectionCard, SeverityBadge, Skeleton } from "../../components/ui/primitives";
import { useI18n } from "../../i18n/i18nContext";
import { localizeFeedTitle } from "../../lib/feedText";
import type { Disruption, DisruptionFeed as Feed, DisruptionKind } from "../../types/dashboard";
import type { LoadState } from "../../state/useCivicFeeds";

const KIND_META: Record<DisruptionKind, { label: string; Icon: typeof Zap }> = {
  power: { label: "Power", Icon: Zap },
  road: { label: "Roads", Icon: TrafficCone },
  transit: { label: "Transit", Icon: TrainFront },
  water: { label: "Water", Icon: Droplets },
};

const PAGE = 6;

interface Props {
  feed: LoadState<Feed> & { refresh: () => void };
  coverage: boolean;
  nearLabel: string | null;
}

/** Power summaries are generated by CivicOS and translate; road and transit text comes from the City and OC Transpo. */
function FeedItem({ item, nearLabel }: { item: Disruption; nearLabel: string | null }) {
  const { t, locale, relativeTime } = useI18n();
  const { Icon } = KIND_META[item.kind];
  const generated = item.kind === "power";
  const title = generated ? { text: t(item.title), sourceOnly: false } : localizeFeedTitle(item.title, t);
  const sourceLang = locale !== "en" ? "en" : undefined;

  return (
    <li className={`feed-item feed-item--${item.severity}`}>
      <span className="feed-item__icon" aria-hidden="true">
        <Icon size={15} />
      </span>
      <div className="feed-item__body">
        <div className="feed-item__top">
          <SeverityBadge severity={item.severity} />
          {item.distanceKm !== undefined && (
            <span className="feed-item__distance">
              {nearLabel ? t("{distance} km from {place}", { distance: item.distanceKm, place: nearLabel }) : t("{distance} km", { distance: item.distanceKm })}
            </span>
          )}
        </div>
        <p className="feed-item__title" lang={title.sourceOnly ? sourceLang : undefined}>
          {title.text}
        </p>
        {item.detail && (
          <p className="feed-item__detail" lang={generated ? undefined : sourceLang} data-untranslated={!generated && sourceLang ? true : undefined}>
            {generated ? t(item.detail) : item.detail}
          </p>
        )}
        <p className="feed-item__source">
          {item.sourceUrl ? (
            <a href={item.sourceUrl} target="_blank" rel="noreferrer">
              {t(item.source)}
            </a>
          ) : (
            t(item.source)
          )}
          {item.updatedAt && <> · {t("updated {time}", { time: relativeTime(item.updatedAt) })}</>}
        </p>
      </div>
    </li>
  );
}

export default function DisruptionFeed({ feed, coverage, nearLabel }: Props) {
  const { t, tp, relativeTime, formatNumber } = useI18n();
  const [kind, setKind] = useState<DisruptionKind | "all">("all");
  const [limit, setLimit] = useState(PAGE);
  const data = feed.data;

  const counts = useMemo(() => {
    const base: Record<DisruptionKind, number> = { power: 0, road: 0, transit: 0, water: 0 };
    data?.items.forEach((i) => (base[i.kind] += 1));
    return base;
  }, [data]);

  const items = (data?.items ?? []).filter((i) => kind === "all" || i.kind === kind);
  const waterSource = data?.sources.find((s) => s.kind === "water");

  return (
    <SectionCard
      id="disruptions"
      title={t("Ottawa disruptions & outages")}
      icon={<Activity size={16} />}
      actions={
        coverage && (
          <button type="button" className="icon-btn icon-btn--sm" aria-label={t("Refresh disruptions")} onClick={feed.refresh}>
            <RefreshCw size={15} />
          </button>
        )
      }
    >
      {!coverage ? (
        <p className="muted-block">{t("Live disruption feeds are connected for Ottawa. Choose Ontario to see them.")}</p>
      ) : feed.status === "loading" ? (
        <Skeleton lines={4} />
      ) : !data ? (
        <p className="muted-block">{t(feed.error)}</p>
      ) : (
        <>
          {data.power && (
            <p className="power-summary">
              <Zap size={14} aria-hidden="true" />
              <span>
                {tp(
                  "Hydro Ottawa: {count} active outage, {affected} of {served} customers affected",
                  "Hydro Ottawa: {count} active outages, {affected} of {served} customers affected",
                  data.power.outages,
                  { affected: t(data.power.customersAffected), served: formatNumber(data.power.customersServed) },
                )}
              </span>
            </p>
          )}

          <div className="chips" role="group" aria-label={t("Filter disruptions")}>
            <button type="button" className={`chip${kind === "all" ? " chip--active" : ""}`} aria-pressed={kind === "all"} onClick={() => setKind("all")}>
              {t("All")} <span className="chip__count">{data.items.length}</span>
            </button>
            {(Object.keys(KIND_META) as DisruptionKind[]).map((k) => {
              const { label, Icon } = KIND_META[k];
              return (
                <button
                  key={k}
                  type="button"
                  className={`chip${kind === k ? " chip--active" : ""}`}
                  aria-pressed={kind === k}
                  onClick={() => {
                    setKind(k);
                    setLimit(PAGE);
                  }}
                >
                  <Icon size={13} aria-hidden="true" /> {t(label)} <span className="chip__count">{counts[k]}</span>
                </button>
              );
            })}
          </div>

          {kind === "water" && waterSource ? (
            <p className="muted-block">
              {t(waterSource.note ?? "No public feed; Ottawa Public Health posts advisories.")}{" "}
              <a href={waterSource.sourceUrl} target="_blank" rel="noreferrer">
                {t("Check Ottawa Public Health")} <ExternalLink size={11} aria-hidden="true" />
              </a>
            </p>
          ) : items.length === 0 ? (
            <p className="muted-block">{kind === "all" ? t("No active disruptions reported.") : t("No active {kind} disruptions reported.", { kind: t(KIND_META[kind].label).toLowerCase() })}</p>
          ) : (
            <ul className="feed">
              {items.slice(0, limit).map((item) => (
                <FeedItem key={item.id} item={item} nearLabel={nearLabel} />
              ))}
            </ul>
          )}

          {items.length > limit && kind !== "water" && (
            <button type="button" className="link-btn" onClick={() => setLimit((l) => l + PAGE)}>
              {t("Show {count} more of {total}", { count: Math.min(PAGE, items.length - limit), total: items.length - limit })}
            </button>
          )}

          <ul className="sources" aria-label={t("Feed sources")}>
            {data.sources.map((s) => (
              <li key={s.kind} className={`source source--${s.status}`}>
                <span className="source__dot" aria-hidden="true" />
                {t(s.label)}: {t(s.status === "live" ? "live" : s.status === "no-feed" ? "no public feed" : "unavailable")}
              </li>
            ))}
            <li className="source">{t("Updated {time}", { time: relativeTime(data.fetchedAt) })}</li>
          </ul>
        </>
      )}
    </SectionCard>
  );
}
